import raw from './lgpCampaigns.json';
import type { LgpCampaign } from '@/types';

/**
 * Campaign KPIs synced from the LGP analytics engine.
 * Generated by `scripts/sync-lgp.mjs` (see docs/LGP_SYNC.md). When this moves to
 * a live backend (Supabase/Postgres), only this module changes — not the UI.
 */
export const lgpCampaigns = (raw as { campaigns: unknown }).campaigns as unknown as LgpCampaign[];
